### PR TITLE
[WIP]: Bitsmask

### PR DESCRIPTION
**Pull request by darthpelo**
Hi @uraimo, I was busy in the last two weeks, so I decided to create a WIP pull request to show you how I started to change the gyb file and the test file.

I finished the mask for `Int` and `UInt`.
The mask function for bit 8, 16, 32 and 64 is still in progress.

To be honest, I lost the familiar with these operations, so feel free to give me any suggestions you think are necessary or change requests :)

Thanks!

### CODE REVIEW

**Comment by uraimo** [comment]
Hi! Looking at the tests this works like this at the moment: the user gives an integer and depending on the msb boolean one of the two halves is masked out with 1s.
The description was a bit scanty but I was thinking about something simpler, instead of adding a method that masks an integer right away I was thinking of adding a method that generates masks that the user can than use as he pleases.

So, the user should choose how many ones he wants in the mask and if they should start from the msb or lsb.
The main use of this will be to quickly generate masks than will be used to extract a section of a binary struct to read a single specific field.
For example, if you have 32 bits of data with the following structure:

    [6bits: SourceId][6bits: DestinationId][16bits: Payload][4bits: CRC]

you could use this method to extract the destinationId with:
    
    message & (Int32.mask(6,false) << 20)

This should work this way:

    An Int16 with bits: 5 , msb: false
    Result: 0000 0000 0001 1111 = 31

    An Int16 with bits: 5 , msb: true
    Result: 1111 1000 0000 0000 = 63488

To implement this, instead of keep adding 1s to the empty int, shifting each time the pattern left or right, for *bits* times, when msb is true you can easily obtain the same pattern with `pow(2,bits)-1`.
For the msb=false pattern you can just xor `Int.max` with `pow(2,bits)-1` to mirror the previous pattern to the left.
But this technique will likely overflow the integer when the user asks for a number of bits equal to the size of the integer (i.e. bits:32 for an Int32) so that edge case will need to be handled separately.

Thanks again for the time you are putting into this PR.

**Comment by darthpelo** [comment]
Thanks for the clear feedback @uraimo! 
No worries about the misunderstanding, was useful for me to understand how gyb works :)

**Comment by darthpelo** [comment]
@uraimo PR updated.

**Comment by uraimo** [comment]
Perfect! Thoroughly tested too!

**Pull request merged**
